# Config file for loveletter.

database:
  # name can be "dev_telemetry", "test_telemetry" or "telemetry"
  # for dev, qa, and prod databases.
  name: 'telemetry.db'
  trip_purposes: ['Pesca',
                  'Caceria',
                  'Chakra',
                  'Mingas comunitarias',
                  'Deporte',
                  'Salud',
                  'Educacion',
                  'Trabajo',
                  'Turismo',
                  'Asamblea',
                  'Reuniones Comunitarias',
                  'Visitas (Guayusa)',
                  'Aniversario',
                  'Monitoreo Territorial',
                  'Viaje Institucional',
                  'Apoyo Tecnico',
                  'Otro'
                  ]

  captain_config: ["Domingo M",
                   "Mauro Mukucham",
                   "Santiago",
                   "Roberto",
                   "Olger",
                   "Efren",
                   "Federico"
                  ]

cerbo_gx:
  server_ip: '169.254.1.2'

passenger_number:
  min: 0
  max: 40

