# Config file for loveletter.

database:
  # name can be "dev_telemetry", "test_telemetry" or "telemetry"
  # for dev, qa, and prod databases.
  name: 'telemetry.db'
  trip_purposes: ['Pesca',
                  'Caceria',
                  'Chakra',
                  'Mingas comunitarias',
                  'Deporte',
                  'Salud',
                  'Educacion',
                  'Trabajo',
                  'Turismo',
                  'Asamblea',
                  'Reuniones Comunitarias',
                  'Visitas (Guayusa)',
                  'Aniversario',
                  'Monitoreo Territorial',
                  'Viaje Institucional',
                  'Apoyo Tecnico',
                  'Otro'
                  ]

  captain_config: ["Domingo M",
                   "Mauro Mukucham",
                   "Santiago",
                   "Roberto",
                   "Olger",
                   "Efren",
                   "Federico"
                  ]

cerbo_gx:
  server_ip: '169.254.1.2'

passenger_number:
  min: 0
  max: 40

communities_config:
  Sharamentsa:
    - 'Pto. Shuimamus'
    - 'Pto. Napurak'
    - 'Playa'
    - 'Pto. Solar Sharamentsa'
    - 'Finca Gonzalo Esach'
    - 'Finca Isolina Vargas'
    - 'Finca Mercedes Illanes'
    - 'Nantu Canelos'
    - 'Elena Pitiur'
    - 'Ceibo'
    - 'Finca Carlos Wanach'
  Wayusentsa:
    - 'Pto. Principal Wayusentsa'
    - 'Pto. Solar Wayusentsa'
    - 'Pto. Barrio Panki'
    - 'Pto. Barrio Mente'
    - 'Pto. Barrio Napi'
    - 'Pto. Com. Tsekuntsa'
    - 'Pto. Com. Kusutkao'
    - 'Pto. Solar Kapawi'
    - 'Pto. TUNA'
    - 'Finca Federico'
    - 'Finca Efren'
    - 'Finca Angel'
    - 'Finca Sankap'
    - 'Punto Pto. caceria'
    - 'Pto. Rafael'
    - 'Pto. Raul'
  Kapawi:
    - 'B.panki, Pto. Callera'
    - 'B.panki, Pto. Alfredo'
    - 'Pto. Com. Wachirpas'
    - 'Pto. Solar Kapawi'
    - 'Bocana Rio Pastaza'
    - 'Pto. Yawantsa'
  Wichimi:
    - 'Pto. Solar Wichimi'
    - 'Pto. San Luis'
    - 'Pto. Wichimi'
    - 'Finca de Jorge'
    - 'Finca de Domingo'
    - 'Finca de Guillermo'
    - 'Finca de Abel'
    - 'Pto. Barrio San Luiz'
