# Config file for loveletter.

database:
  # name can be "dev_telemetry", "test_telemetry" or "telemetry"
  # for dev, qa, and prod databases.
  name: 'telemetry.db'
  trip_purposes: ['Asamblea',
                  'Chacra',
                  'Deporte',
                  'Escuela',
                  'Invitacion Comunitario',
                  'Minga',
                  'Paseo',
                  'Pesca',
                  'Salud',
                  'Traslado Empleados',
                  'Turismo',
                  'Otros']

cerbo_gx:
  server_ip: '169.254.1.2'

passenger_number:
  min: 0
  max: 40

